### ISSUE TITLE
Setup Github Actions for clang linter

### ISSUE THREAD

**Issue by zouzias** [zouzias/microgbt#28]
As a developer, I want to have a consistent code formatting for c++:

Suggestion:

```
 clang-format-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: DoozyX/clang-format-lint-action@v0.5
        with:
          source: "./src"
          extensions: "h,cpp"
          clangFormatVersion: 9

```
